version: '3'

services:

  mysql: # 服务名
    image: mysql:8.0 # 镜像和版本
    ports:
      - "${MYSQLPORT}:3306" # 本地端口:容器内部端口
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro # 本地配置文件挂载
      - ./mysql/data:/var/lib/mysql/:rw # 把源数据保存到外面来
    restart: always # 开机启动
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # 密码
    container_name: mysql # 别名

  nginx:
    image: nginx:1.19.2
    ports:
      - "80:80" # 2 主机端口:容器端口
      - "443:443" # 2 主机端口:容器端口
    volumes:
      - ./wwwroot:/wwwroot:rw # 2 网站的目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw # 2 nginx主配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d:rw # 2 nginx的配置目录，nginx会加载整个合法命名的目录下所有配置
      - ./nginx/logs:/etc/nginx/logs:rw # 2.3.3  nginx网站访问日志记录
    restart: always
    container_name: nginx
    depends_on:
      - "php53" # 依赖于php53

  php53:
    image: leleos/php-fpm:5.3
    ports:
      - "9000:9000"
    volumes:
      - ./wwwroot:/wwwroot:rw
    restart: always
    container_name: php53
    depends_on:
      - "mysql" # 依赖于 nginx

